.TH "targetver.h" 3 "Mon Nov 8 2010" "Version 1" "CS684_course_project_group5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
targetver.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fB_WIN32_WINNT\fP   0x0600"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define _WIN32_WINNT   0x0600"
.PP
Definition at line 11 of file targetver.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for CS684_course_project_group5 from the source code.
