.TH "includes.h" 3 "Mon Nov 8 2010" "Version 1" "CS684_course_project_group5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <assert.h>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <list>\fP
.br
\fC#include <cv.h>\fP
.br
\fC#include <highgui.h>\fP
.br
\fC#include <math.h>\fP
.br
\fC#include <atlstr.h>\fP
.br
\fC#include 'point.h'\fP
.br
\fC#include 'vector_extract.h'\fP
.br
\fC#include 'operations.h'\fP
.br
\fC#include 'stdafx.h'\fP
.br
\fC#include 'serialcomm.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for CS684_course_project_group5 from the source code.
