.TH "point.h" 3 "Mon Nov 8 2010" "Version 1" "CS684_course_project_group5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
point.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpoint\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBINF\fP   56"
.br
.ti -1c
.RI "#define \fBPI\fP   3.14159265"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define INF   56"
.PP
Definition at line 1 of file point.h.
.SS "#define PI   3.14159265"
.PP
Definition at line 2 of file point.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for CS684_course_project_group5 from the source code.
