.TH "serialcomm.h" 3 "Mon Nov 8 2010" "Version 1" "CS684_course_project_group5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
serialcomm.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBserialOpen\fP (CString PortSpecifier)"
.br
.ti -1c
.RI "bool \fBWriteComPort\fP (int number)"
.br
.ti -1c
.RI "int \fBwriteOnBot\fP (int *moves, int length)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "HANDLE \fBhPort\fP"
.br
.ti -1c
.RI "DWORD \fBbyteswritten\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool serialOpen (CString PortSpecifier)"
.PP
Definition at line 4 of file serialcomm.h.
.SS "bool WriteComPort (int number)"
.PP
Definition at line 27 of file serialcomm.h.
.SS "int writeOnBot (int * moves, int length)"
.PP
Definition at line 34 of file serialcomm.h.
.SH "Variable Documentation"
.PP 
.SS "DWORD \fBbyteswritten\fP"
.PP
Definition at line 2 of file serialcomm.h.
.SS "HANDLE \fBhPort\fP"
.PP
Definition at line 1 of file serialcomm.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for CS684_course_project_group5 from the source code.
