.TH "stdafx.h" 3 "Mon Nov 8 2010" "Version 1" "CS684_course_project_group5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stdafx.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'targetver.h'\fP
.br
\fC#include <stdio.h>\fP
.br
\fC#include <tchar.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for CS684_course_project_group5 from the source code.
